const countryNameMap = {
    // 亚洲
    "China": "中国",
    "Japan": "日本",
    "South Korea": "韩国",
    "North Korea": "朝鲜",
    "India": "印度",
    "Vietnam": "越南",
    "Thailand": "泰国",
    "Malaysia": "马来西亚",
    "Singapore": "新加坡",
    "Indonesia": "印度尼西亚",
    "Philippines": "菲律宾",
    "Pakistan": "巴基斯坦",
    "Bangladesh": "孟加拉国",
    "Sri Lanka": "斯里兰卡",
    "Myanmar": "缅甸",
    "Cambodia": "柬埔寨",
    "Laos": "老挝",
    "Nepal": "尼泊尔",
    "Mongolia": "蒙古",
    "Kazakhstan": "哈萨克斯坦",
    "Uzbekistan": "乌兹别克斯坦",
    "Turkmenistan": "土库曼斯坦",
    "Kyrgyzstan": "吉尔吉斯斯坦",
    "Tajikistan": "塔吉克斯坦",
    "Iran": "伊朗",
    "Iraq": "伊拉克",
    "Saudi Arabia": "沙特阿拉伯",
    "United Arab Emirates": "阿联酋",
    "Turkey": "土耳其",
    "Israel": "以色列",
    "Palestine": "巴勒斯坦",
    "Jordan": "约旦",
    "Syria": "叙利亚",
    "Lebanon": "黎巴嫩",
    "Kuwait": "科威特",
    "Oman": "阿曼",
    "Qatar": "卡塔尔",
    "Yemen": "也门",
    "Afghanistan": "阿富汗",
    "Georgia": "格鲁吉亚",
    "Armenia": "亚美尼亚",
    "Azerbaijan": "阿塞拜疆",

    // 欧洲
    "Greenland": "格陵兰岛",
    "Russia": "俄罗斯",
    "Germany": "德国",
    "France": "法国",
    "United Kingdom": "英国",
    "Italy": "意大利",
    "Spain": "西班牙",
    "Portugal": "葡萄牙",
    "Netherlands": "荷兰",
    "Belgium": "比利时",
    "Switzerland": "瑞士",
    "Austria": "奥地利",
    "Greece": "希腊",
    "Sweden": "瑞典",
    "Norway": "挪威",
    "Denmark": "丹麦",
    "Finland": "芬兰",
    "Ireland": "爱尔兰",
    "Poland": "波兰",
    "Czech Republic": "捷克",
    "Slovakia": "斯洛伐克",
    "Hungary": "匈牙利",
    "Romania": "罗马尼亚",
    "Bulgaria": "保加利亚",
    "Serbia": "塞尔维亚",
    "Croatia": "克罗地亚",
    "Slovenia": "斯洛文尼亚",
    "Bosnia and Herzegovina": "波黑",
    "Montenegro": "黑山",
    "North Macedonia": "北马其顿",
    "Albania": "阿尔巴尼亚",
    "Ukraine": "乌克兰",
    "Belarus": "白俄罗斯",
    "Estonia": "爱沙尼亚",
    "Latvia": "拉脱维亚",
    "Lithuania": "立陶宛",
    "Moldova": "摩尔多瓦",
    "Iceland": "冰岛",
    "Luxembourg": "卢森堡",
    "Monaco": "摩纳哥",
    "Malta": "马耳他",

    // 美洲
    "Belize": "伯利兹",
    "United States of America": "美国",
    "Canada": "加拿大",
    "Mexico": "墨西哥",
    "Brazil": "巴西",
    "Argentina": "阿根廷",
    "Chile": "智利",
    "Colombia": "哥伦比亚",
    "Peru": "秘鲁",
    "Venezuela": "委内瑞拉",
    "Ecuador": "厄瓜多尔",
    "Bolivia": "玻利维亚",
    "Paraguay": "巴拉圭",
    "Urguay": "乌拉圭",
    "Cuba": "古巴",
    "Jamaica": "牙买加",
    "Panama": "巴拿马",
    "Costa Rica": "哥斯达黎加",
    "Guatemala": "危地马拉",
    "Honduras": "洪都拉斯",
    "Dominican Republic": "多米尼加",

    // 大洋洲
    "Australia": "澳大利亚",
    "New Zealand": "新西兰",
    "Papua New Guinea": "巴布亚新几内亚",
    "Fiji": "斐济",

    // 非洲
    "Central African Republic": "中非共和国",
    "Ivory Coast": "科特迪瓦",
    "Benin": "贝宁",
    "Burundi": "布隆迪",
    "Egypt": "埃及",
    "South Africa": "南非",
    "Nigeria": "尼日利亚",
    "Ethiopia": "埃塞俄比亚",
    "Kenya": "肯尼亚",
    "Algeria": "阿尔及利亚",
    "Morocco": "摩洛哥",
    "Libya": "利比亚",
    "Sudan": "苏丹",
    "Tunisia": "突尼斯",
    "Ghana": "加纳",
    "Cote d'Ivoire": "科特迪瓦",
    "Senegal": "塞内加尔",
    "Democratic Republic of the Congo": "刚果金",
    "Republic of the Congo": "刚果布",
    "Angola": "安哥拉",
    "Tanzania": "坦桑尼亚",
    "Uganda": "乌干达",
    "Zambia": "赞比亚",
    "Zimbabwe": "津巴布韦",
    "Madagascar": "马达加斯加",
    "Mauritius": "毛里求斯",
    "Antarctica": "南极洲",
    "French Southern and Antarctic Lands": "法属南半球和南极领地",
    "Bermuda": "百慕大",
    "Burkina Faso": "布基纳法索",
    "The Bahamas": "巴哈马",
    "Bhutan": "不丹",
    "Djibouti": "吉布提",
    "Falkland Islands": "福克兰群岛",
    "Cameroon": "喀麦隆",
    "Botswana": "博茨瓦纳",
    "Northern Cyprus": "北塞浦路斯",
    "Cyprus": "塞浦路斯",
    "Equatorial Guinea": "赤道几内亚",
    "Mozambique": "莫桑比克",
    "Kosovo": "科索沃",
    "Malawi": "马拉维",
    "New Caledonia": "新喀里多尼亚",
    "Gambia": "冈比亚",
    "Guinea": "几内亚",
    "Guinea Bissau": "几内亚比绍",
    "Puerto Rico": "波多黎各",
    "Somaliland": "索马里兰",
    "Somalia": "索马里",
    "South Sudan": "南苏丹",
    "Swaziland": "斯威士兰",
    "Trinidad and Tobago": "特立尼达和多巴哥",
    "United Republic of Tanzania": "坦桑尼亚联合共和国",
    "West Bank": "约旦河西岸",
    "Western Sahara": "西撒哈拉",
    "Eritrea": "厄立特里亚",
    "Guyana": "圭亚那",
    "Suriname": "苏里南",
    "Haiti": "海地",
    "Mali": "马里",
    "Niger": "尼日尔",
    "Chad": "乍得",
    "Gabon": "加蓬",
    "Namibia": "纳米比亚",
    "Mauritania": "毛里塔尼亚",
    "Togo": "多哥",
    "Sierra Leone": "塞拉利昂",
    "Liberia": "利比里亚",
    "Lesotho": "莱索托",
    "Solomon Islands": "所罗门群岛",
    "Vanuatu": "瓦努阿图"
};